### ISSUE TITLE
getHttpRpcClient `onRequest` change request , should send request

### ISSUE THREAD

**Issue by 841660202** [wevm/viem#2741] opened 2024-09-19 03:31 UTC
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

latest

### Current Behavior

[https://github.com/wevm/viem/blob/15c71b6dacc3abe9ed0ac0fc9c21c9b70c2072e5/src/utils/rpc/http.ts#L103-L105](https://github.com/wevm/viem/blob/15c71b6dacc3abe9ed0ac0fc9c21c9b70c2072e5/src/utils/rpc/http.ts#L103-L105)

`onRequest` change request , should send request

### Expected Behavior

If onRequest change request, should send request

### Steps To Reproduce

```
createPublicClient({
      chain: chain,
      transport:  http(chain?.rpcUrls.default.http[0], {
        onFetchRequest: async (request: Request) => {
          // const bodyText = await request.clone().text()
          // const body = JSON.parse(bodyText)
          // const method = Array.isArray(body) ? body[0].method : body.method
          // request.headers.set('X-Proxy-Jsonrpc-Method', method)
          // console.log('request', request)
        },
     })
  })
```

### Anything else?

[https://github.com/wevm/viem/blob/15c71b6dacc3abe9ed0ac0fc9c21c9b70c2072e5/src/utils/rpc/http.ts#L103-L105](https://github.com/wevm/viem/blob/15c71b6dacc3abe9ed0ac0fc9c21c9b70c2072e5/src/utils/rpc/http.ts#L103-L105)

`onRequest` change request , should send request

`const response = await fetch(url, init) `send `url `& `init`, here should `request `

This is MDN https://developer.mozilla.org/zh-CN/docs/Web/API/Request
```
fetch(request)
  .then((response) => {
    if (response.status === 200) {
      return response.json();
    } else {
      throw new Error("Something went wrong on API server!");
    }
  })
  .then((response) => {
    console.debug(response);
    // …
  })
  .catch((error) => {
    console.error(error);
  });
```

**Comment by jxom** [comment] 2024-09-19 04:57
What is the issue? Not too sure what you mean – please properly fill out a bug report including a minimal reproducible example.

**Comment by jxom** [comment] 2024-09-19 04:58
possibly dupe of https://github.com/wevm/viem/issues/2630

**Closed** 2024-09-19 04:58 UTC
Labels: needs reproduction
